// apps/web-client/src/app/lib/primitives/text/text.tsx
import React from 'react';

/**
 * Text primitive — the minimal, indivisible building block for inline text content.
 *
 * Renders children inside a <span>. Styling is the responsibility of consuming
 * molecules (Text Cell) and organisms — only `className` is forwarded so that
 * presentation classes (e.g., `truncate`, `wrap`) can be applied by the caller
 * without this primitive owning any opinion about layout.
 *
 * Layer: lib/primitives — more fundamental than an atom; genuinely indivisible.
 */
export interface TextProps {
  readonly children?: React.ReactNode;
  /**
   * Optional Tailwind utility classes forwarded to the <span>.
   * The primitive itself applies no classes; callers own presentation.
   */
  readonly className?: string;
}

export function Text({ children, className }: TextProps): React.ReactElement {
  return <span className={className}>{children}</span>;
}

// apps/vue-client/src/app/lib/primitives/text/Text.vue
<script setup lang="ts">
/**
 * Text primitive — the minimal, indivisible building block for inline text content.
 *
 * Renders `text` prop inside a <span> when provided; falls back to the default
 * slot so callers can project content. Owns no layout opinion — styling (e.g.
 * `truncate`) is applied by the consuming molecule via class forwarding.
 *
 * Layer: lib/primitives — more fundamental than an atom; genuinely indivisible.
 *
 * Vue note: `text` prop takes precedence; slot renders when `text` is absent.
 * Callers forward Tailwind utility classes via the standard Vue fallthrough
 * attribute mechanism (no explicit class prop needed).
 */
defineProps<{ text?: string }>();
</script>

<template>
  <span><template v-if="text != null">{{ text }}</template><slot v-else /></span>
</template>
