// apps/vue-client/src/app/lib/organisms/data-table/DataTable.vue
<script setup lang="ts" generic="TRow">
/**
 * Data Table — organism.
 *
 * Top-level shell that accepts DataTableProps<TRow> and renders Table Rows from
 * the `data` array using the `columns` configuration. Cell rendering is dispatched
 * to the cell-type registry — this organism does not switch on `column.type` itself.
 *
 * Layer: lib/organisms — owns the coordination of header, body, row, and cell
 * structure; consumes the framework registry seam.
 *
 * NGI-12 scope:
 *   - Renders rows from data / columns (Default State).
 *   - Accepts isLoading / error / emptyStateMessage as props (no distinct UI yet —
 *     those state organisms ship in later tickets: US-05, US-06).
 *   - Hover State: pure CSS `hover:bg-slate-50` on each Table Row (US-04).
 *   - Native table semantics: <table>, <thead>, <tbody>, <tr>, <th scope="col">, <td>.
 *
 * Hover State: `hover:bg-slate-50` on the <tr> — pure CSS Tailwind, no JS event
 * handlers. Background-color only; cell content and layout are unaffected.
 *
 * Reactivity: props are bound directly in the template `v-for`. No snapshot into
 * a plain local constant outside a computed — that would break Vue reactivity
 * (react-to-prop-change AC item 3). (reactivity.md rule honored.)
 *
 * Canonical name comments label each structural section so later tickets can
 * extract them as named components without renaming.
 */
import type { DataTableProps, CellAlignment } from '@test-project/data-table';
import { resolveCellRenderer } from '../../framework/cell-registry';

// isLoading / error / emptyStateMessage are accepted in props but no distinct
// UI is rendered in NGI-12 — those state organisms ship in later tickets (US-05, US-06).
const props = defineProps<DataTableProps<TRow>>();

/** Map CellAlignment → Tailwind text-align utility class. */
function alignClass(align?: CellAlignment): string {
  if (align === 'end') return 'text-right';
  if (align === 'center') return 'text-center';
  if (align === 'start') return 'text-left';
  return '';
}

/**
 * Return a stable key string for a row.
 *
 * Strategy: prefer the value of the first column (converted to string) since
 * it is the most human-meaningful stable identifier. Fall back to the array
 * index with a DEV warning so the developer knows they should supply a stable
 * `id` field or ensure first-column values are unique.
 */
function rowKey(row: TRow, index: number): string | number {
  const firstCol = props.columns[0];
  if (firstCol) {
    const val = row[firstCol.key as keyof TRow];
    if (val != null && val !== '') return String(val);
  }
  if (import.meta.env.DEV) {
    console.warn(
      '[DataTable] Could not derive a stable row key from the first column value. ' +
        'Falling back to array index. Provide non-empty first-column values or add an `id` field ' +
        'to ensure stable keys during re-renders.',
    );
  }
  return index;
}
</script>

<template>
  <!-- Data Table -->
  <table class="w-full border-collapse text-sm">
    <!-- Table Header -->
    <thead>
      <tr>
        <!-- Table Header Cell -->
        <th
          v-for="column in props.columns"
          :key="column.id ?? column.key"
          scope="col"
          :class="[
            'border-b border-slate-200 px-4 py-3 text-left font-semibold text-slate-700',
            alignClass(column.align),
          ]"
        >
          {{ column.header }}
        </th>
      </tr>
    </thead>

    <tbody>
      <!-- Table Row — hover:bg-slate-50 is the Hover State (US-04).
           Pure CSS: no JS state, no event handlers, background-color only. -->
      <tr
        v-for="(row, index) in props.data"
        :key="rowKey(row, index)"
        class="border-b border-slate-100 last:border-0 hover:bg-slate-50"
      >
        <!-- Table Cell -->
        <td
          v-for="column in props.columns"
          :key="column.id ?? column.key"
          :class="['px-4 py-3 text-slate-900', alignClass(column.align)]"
        >
          <component
            :is="resolveCellRenderer(column.type)"
            :value="row[column.key as keyof TRow]"
            :column="column"
            :row="row"
          />
        </td>
      </tr>
    </tbody>
  </table>
</template>

// apps/angular-client/src/app/lib/organisms/data-table/data-table.component.ts
/**
 * Data Table organism.
 *
 * Top-level shell that accepts the DataTableProps<T> contract and renders
 * one Table Row per data item, dispatching each cell to the registered
 * cell-type renderer via NgComponentOutlet.
 *
 * Layer: lib/organisms/data-table/ — owns rendering coordination.
 * Canonical name: Data Table (CLAUDE.md §4).
 * Selector: app-data-table.
 *
 * State props accepted (organisms for them ship in later tickets):
 *   - isLoading: boolean — Loading State organism (US-06)
 *   - error: unknown — Error State organism (future ticket)
 *   - emptyStateMessage: string | undefined — Empty State organism (US-05)
 *
 * No domain types. No domain imports.
 *
 * @tanstack/table-core wiring is deferred — see design.md "Decisions Deferred".
 */

import {
  ChangeDetectionStrategy,
  Component,
  inject,
  input,
  Type,
} from '@angular/core';
import { NgComponentOutlet } from '@angular/common';
import type { ColumnConfig, CellType } from '@test-project/data-table';
import {
  CELL_RENDERER_REGISTRY,
} from '../../framework/cell-registry';
import { TextCellComponent } from '../../molecules/cells/text-cell/text-cell.component';
import type { CellRendererComponent } from '../../framework/cell-registry.types';

@Component({
  selector: 'app-data-table',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [NgComponentOutlet],
  templateUrl: './data-table.component.html',
})
export class DataTableComponent<TRow extends object> {
  // ---- Inputs (one per DataTableProps<T> field) ----

  /**
   * Column definitions that drive Table Header Cell labels and cell
   * rendering. Columns are rendered in declared order.
   */
  readonly columns = input.required<readonly ColumnConfig<TRow>[]>();

  /**
   * Rows to render. One Table Row is emitted per element.
   * Order matches the source array.
   */
  readonly data = input.required<readonly TRow[]>();

  /**
   * When true the table is in Loading State.
   * Loading State organism ships in US-06 — prop accepted now so that
   * ticket is a purely additive change.
   */
  readonly isLoading = input<boolean>(false);

  /**
   * Non-null when the table is in Error State.
   * Error State organism ships in a later ticket.
   */
  readonly error = input<unknown>(undefined);

  /**
   * Copy to show in the Empty State organism (US-05).
   * The Empty State organism ships in a later ticket; prop carried now
   * so that ticket is a purely additive change.
   */
  readonly emptyStateMessage = input<string | undefined>(undefined);

  // ---- Registry ----

  private readonly registry = inject(CELL_RENDERER_REGISTRY);

  // ---- Track-by helpers ----

  /**
   * TrackBy for @for over columns.
   * Uses col.id when present; falls back to col.key.
   */
  trackColumn(_index: number, col: ColumnConfig<TRow>): string {
    return col.id ?? col.key;
  }

  /**
   * TrackBy for @for over rows.
   * Uses the array index; a stable row identifier can replace this
   * in a later ticket without API changes.
   */
  trackRow(index: number, _row: TRow): number {
    return index;
  }

  // ---- Cell-value accessor ----

  /**
   * Extracts the cell value from a row for the given column key.
   * Typed as unknown because the registry boundary cannot guarantee
   * a narrower type; each renderer coerces or narrows.
   */
  cellValue(row: TRow, key: string): unknown {
    return (row as Record<string, unknown>)[key];
  }

  // ---- Registry dispatcher ----

  /**
   * Returns the renderer component for the given CellType.
   *
   * In dev mode: throws when the type is not registered so that
   * missing registrations surface immediately during development.
   * In production: falls back to TextCellComponent to avoid a blank cell.
   */
  rendererFor(type: CellType): Type<unknown> {
    const renderer = this.registry.get(type);

    if (!renderer) {
      if (typeof ngDevMode !== 'undefined' && ngDevMode) {
        throw new Error(
          `[DataTableComponent] No renderer registered for cell type "${type}". ` +
            `Register it in CELL_RENDERER_REGISTRY via app.config.ts.`,
        );
      }
      // Production fallback: render raw value as text.
      return TextCellComponent as CellRendererComponent;
    }

    return renderer;
  }

  /**
   * Builds the inputs object passed to NgComponentOutlet for a cell.
   * Every renderer receives value, column, and row so that complex
   * future renderers (Avatar Cell, Icon + Text Cell) have full context.
   */
  cellInputs(
    row: TRow,
    col: ColumnConfig<TRow>,
  ): Record<string, unknown> {
    return {
      value: this.cellValue(row, col.key),
      column: col,
      row,
    };
  }
}

<!-- Data Table -->
<table class="w-full border-collapse text-sm">

  <!-- Table Header -->
  <thead>
    <tr>
      @for (col of columns(); track trackColumn($index, col)) {
        <!-- Table Header Cell -->
        <th
          scope="col"
          class="border-b border-slate-200 px-4 py-3 text-left font-semibold text-slate-700"
          [class.text-right]="col.align === 'end'"
          [class.text-center]="col.align === 'center'"
        >
          {{ col.header }}
        </th>
      }
    </tr>
  </thead>

  <!-- Table Body -->
  <tbody>
    @for (row of data(); track trackRow($index, row)) {
      <!-- Table Row -->
      <tr class="border-b border-slate-100 last:border-0">
        @for (col of columns(); track trackColumn($index, col)) {
          <!-- Table Cell -->
          <td
            class="px-4 py-3 text-slate-900"
            [class.text-right]="col.align === 'end'"
            [class.text-center]="col.align === 'center'"
          >
            <ng-container
              *ngComponentOutlet="
                rendererFor(col.type);
                inputs: cellInputs(row, col)
              "
            />
          </td>
        }
      </tr>
    }
  </tbody>

</table>
