// apps/vue-client/src/app/lib/molecules/cells/text-cell/TextCell.vue
<script setup lang="ts" generic="TRow">
/**
 * Text Cell — molecule that renders a plain-text value inside the Text primitive.
 *
 * Layer: lib/molecules/cells — a focused composition of a primitive serving one role
 * (the Text Cell renderer). Canonical name per CLAUDE.md §4.
 *
 * `value` is typed `unknown` because the cell-type registry receives it from the
 * generic row type at runtime; this molecule coerces to string so the Text primitive
 * always receives a string or empty string.
 *
 * `column` and `row` are accepted for forward compatibility with multi-field cells
 * and Text-specific column options (truncate vs wrap, maxLines) that will live on
 * TextColumnConfig in a later ticket.
 *
 * Truncation: `truncate` class applied to the Text primitive wrapper so long values
 * are clipped with an ellipsis. Matches the React Text Cell and ui-ux-expectations.md
 * default truncation behavior.
 */
import { computed } from 'vue';
import type { ColumnConfig } from '@test-project/data-table';
import Text from '../../../primitives/text/Text.vue';

const props = defineProps<{
  value: unknown;
  column?: ColumnConfig<TRow>;
  row?: TRow;
}>();

// Derive display value — coerce to string, never derive in template (reactivity.md).
const displayValue = computed(() => (props.value == null ? '' : String(props.value)));
</script>

<template>
  <!-- Text Cell — truncate applies overflow-hidden + text-overflow:ellipsis + white-space:nowrap -->
  <Text :text="displayValue" class="truncate" />
</template>

// apps/angular-client/src/app/lib/molecules/cells/text-cell/text-cell.component.ts
/**
 * Text Cell molecule.
 *
 * Concrete cell renderer for columns where `column.type === 'text'`.
 * Coerces the incoming value to a string and delegates rendering to
 * the Text primitive. This is the only cell-type renderer shipped
 * in NGI-12.
 *
 * Layer: lib/molecules/cells/ — focused cell renderer; composes one primitive.
 * Canonical name: Text Cell (CLAUDE.md §4).
 * Selector: app-text-cell.
 *
 * No domain types. No domain imports.
 */

import { ChangeDetectionStrategy, Component, computed, input } from '@angular/core';
import type { ColumnConfig } from '@test-project/data-table';
import { TextComponent } from '../../../primitives/text/text.component';

@Component({
  selector: 'app-text-cell',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [TextComponent],
  template: `<app-text [text]="displayValue()" />`,
})
export class TextCellComponent {
  /**
   * Raw cell value from the row. Typed as unknown because the registry
   * boundary cannot guarantee a narrower type — the Text Cell coerces
   * it to string.
   */
  readonly value = input<unknown>();

  /**
   * The column configuration driving this cell. Provided by the Data
   * Table shell via NgComponentOutlet inputs.
   */
  readonly column = input<ColumnConfig<unknown>>();

  /**
   * The full row object. Provided for future cell types that need
   * multi-field access (e.g., Icon + Text Cell). Text Cell ignores it.
   */
  readonly row = input<unknown>();

  /** Coerces value to a string for the Text primitive. */
  readonly displayValue = computed<string>(() => String(this.value() ?? ''));
}
